# Generated by Django 3.1.1 on 2024-10-11 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20241011_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='sqft',
            new_name='sqm',
        ),
    ]
